### ISSUE TITLE
Métodos para setear 0 en hardware

### ISSUE THREAD

**Issue by MaxiJuarez33** [MaxiJuarez33/ProyectoFinal-Informatica2#2]

**Comment by fabriziodebiaggio** [comment]
Idea de cómo calibrarlo...
Para empezar el mecanismo contaría con dos motores paso a paso, uno con el eje vertical y el otro horizontal.
Ambos tendrían un disco con un agujero que pasaría por el medio de un sensor óptico de tipo herradura para encontrar el cero.
El movimiento con el eje vertical tendría un módulo de brújula magnética.

La lógica sería la siguiente...
Primero encuentra el cero del movimiento vertical. Desde ahí empieza a contar los pasos hasta calibrarse con el Norte magnético. Después al saber cómo está posicionado se acomoda de acuerdo a los datos obtenidos de la web.

Otra idea descartada es la de utilizar cuatro pistones (uno en cada esquina). La complicación acá está en que se depende de que la instalación haya sido adecuada, es decir que quede bien orientado con respecto a los puntos cardinales.

**Comment by fabriziodebiaggio** [comment]
# TODAS LAS CONSIDERACIONES

### Encoder Absoluto
- Ventaja: conocer la posición absoluta del eje en todo momento. 
- Desventaja: alto costo, no se justifica el gasto.

Debido a esto se opta por elegir una opción mucho más simple, entre ellas podía ser:

### Contactos Mecánicos
- Finales de carrera o algun contacto mucho más simple que cierre el circuito al tocarse y marque el punto cero. No se lleva a cabo para no limitar el giro con un final de carrera ni para no depender de partes mecanicas que cierren el circuito.

### Sensores Ópticos
- La idea primitiva es la que terminó siendo la mejor en sentido de simplicidad y costos. Originalmente la idea es utilizar un sensor tipo horquilla/herradura por el cual pasaría un disco con un agujero.

## Funcionamiento del sensado del cero:
- Para el _Azimuth_ (eje vertical): el agujero que indica el cero coincide paralelamente con el eje de la _Altitud_ (eje horizontal).
- Para la _Altitud_ (eje horizontal): el agujero que indica el cero coincide con la posicion paralela al suelo de la montura (cero inclinación respecto al suelo).
