### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by MaxiJuarez33** [MaxiJuarez33/ProyectoFinal-Informatica2#7]
### Tirar ideas de sensores que sensen, accionadores que accionen y demas cosas que podamos usar para meterle

**Comment by fabriziodebiaggio** [comment]
Para que todos veamos lo mismo primero voy a asegurarme de que todos tengamos la misma imagen en la cabeza al pensar en domotizar un camper para pick up.... les dejo este link para que vean una de producción cordobesa https://www.cinziavehiculos.com/AR/4/Productos/Campers/Uritorco

## ¿Qué se puede medir y qué hacer con eso?

### Electricidad:
Producción - Consumo - Nivel de Batería
Se va a producir de dos maneras diferentes... paneles y por el andar de la camioneta (se conecta al mismo sistema que carga la batería de la misma). Ademas podría tener un enchufe externo para poder conectarlo en campings que tengan esa posibilidad (en este caso no habría problema de nada, podría hasta haber un sistema que si se conectó una fuente externa deja de usar las baterías para así prolongar su vida util).
En base a esto se puede realizar un software que optimice el consumo dandole prioridad siempre a la heladera.
Ejemplo: por la hora se sabe que es de noche, el panel por lo tanto no genera, no se está andando en camioneta por lo tanto no se genera de esa manera tampoco, hay luces prendidas, cosas enchufadas, etc y queda 25% de bateria... le corta la corriente a todo lo demas para que no se quede sin la heladera.

### Temperatura: 
Interna - Externa
Va a haber valores por default y sino el usuario puede setearlos. La idea es que si adentro hace calor y afuera está fresco se prendan automaticamente dos ventiladores, uno estaria adelante arriba, tirando a la cama de arriba y el otro sería el extractor de la cocina, así habria un buen flujo de aire. Si hace calor afuera se prendería el aire acondicionado a una temperatura seteable o por default. Lo mismo si hace frío se prenderia el aire en calor.

### Tanques: 
Tienen dos o tres tanques de agua diferentes, uno de aguas blancas (limpia), grises (la sucia) y negras (del inodoro). Algunos para reducir espacio juntan grises y negras. Se pueden sensar y avisar si se está quedando sin (blancas) o llenando (grises/negras).

### Opcional:
Para que en caso de que guarde bateria para la heladera podría haber una luz de bajo consumo que quede habilitada, esto para que no quede a oscuras. En caso de hacerlo así habría dos salidas, una cortaría la fase para todo y otra solo para esta luz de emergencia.
También podría ser un dia de mucho calor y resulta que la bateria se gastó por usar mucho el aire, entonces podría optimizarse mejor aun de manera que primero no deje el aire andando tanto tiempo seguido, sino que lo vaya cortando o bajando (no se si ese tipo de aires lo hacen, por lo general todos los de las casas cuando llegaron a la temperatura en vez de cortar bajan porque gasta menos que volver a encenderlo... se verá esto). Pero también se puede hacer que aunque está guardando bateria para la heladera considere la ventilación, entonces tal vez no usar el aire pero si los ventiladores muy despacito pero que no sea un horno.

Seguridad, se pueden agregar sensores en las ventanas y puertas y de movimiento, alarma y demás. 

### PINES:
Teniendo en cuenta lo dicho se necesitarian:
2 salidas para las dos lineas (uso normal y luz de emergencia)
1 salida para la ventilacion
+1 salida para el aire acondicionado (no se con exactitud cuántas se necesitan para manejarlo, tal vez sean 2)
2 sensores de temperatura
3  para sensores de tanques 
extras para seguridad


Si les parece que conté mal o les gustaría agregar más cosas comentenlo
