### ISSUE TITLE
Requisitos

### ISSUE THREAD

**Issue by MaxiJuarez33** [MaxiJuarez33/ProyectoFinal-Informatica2#8]
### En base a las cosas del hardware, ir poniendo uno por uno los requisitos que deberia cumplir dicho elemento, de ser posible que sea lo mas amplio posible y que incluya todo el funcionamiento, incluido software

**Comment by fabriziodebiaggio** [comment]
## PINES Y SUS USOS

- 1 salida para cortar la línea de iluminación (En esta linea de 12VCC solo estarían conectadas las luces y podría ser un ventilador tambien para mover el aire interno y que se maneja manualmente).
- 1 salida para la luz de emergencia (Esta luz se prendería en los casos que el sistema decida guardar energia para la heladera 12VCC).
- 1 salida para la línea de tomas (Esta es la única línea de 220VCA y sería para conectar cosas como secador de pelo, cargadores de celulares, computadora, cosas del hogar que te llevas de viaje básicamente).
- 1 salida para la ventilación automatica (si sobra una salida podría hacerse una para el ventilador que mete aire y otro para el extractor, ademas hacer un circuito combinado para prenderlos tanto manualmente o por el micro, con este sistema lo que se logra es crear un flujo de aire que se renueva).
- 1 salida para cortar la bomba (la idea es cortarle la corriente antes de que se quede sin agua el tanque).
-  1/2 salidas para el aire acondicionado (hay que ver cuántos se requieren en la mayoria de los casos o con los modelos que se consiguen por mercado libre).
- 2 entradas para los sensores de temperatura (uno sensa la interna y otro la externa, esto para saber si conviene prender la ventilacion o el aire acondicionado).
- 3 entradas para los sensores capacitivos de los tanques de agua (el de agua blanca avisa cuando se está quedando sin y ademas se corta la bomba, los otros dos avisan cuando se están llenando).
- 6 pines para medir la corriente y el voltaje y así saber la potencia (uno mide la generada por el panel solar, otro por el alternador de la camioneta y el ultimo mide la corriente consumida).
- Se le podría incluir un llaverito de alarma, como el del auto.

Agreguen algo si les parece que me estoy olvidando o si les gustaría poner más cosas. Me parece que con lo escrito se cubre todo lo principal que sería administrar los recursos electricos, aereos y líquidos.

**Comment by fabriziodebiaggio** [comment]
El sistema deberia estar midiendo constantemente cuánta energía está generando, cuánta tiene en la batería y cuánta consume.
De ahí estimar qué pasaría si dichos datos se mantienen por determinado periodo de tiempo, por ejemplo si sabe que es de noche y hay muchas cosas enchufadas dentro de 2 horas capaz se termina la batería entonces en base a eso determina si entrar o no en modo ahorro. 
Al entrar en modo ahorro corta todas las lineas y habilita solo la de luz de emergencia. Como pueden ver la heladera se conecta directo, no la controla nada más que su software interno.
La razon de que la ventilacion tenga su propia línea no es para poder prenderlos y apagarlos ya que por un circuito combinado se puede hacer, sino que es para que si entró en modo ahorro de energia pero adentro hace mucho calor prenda de vez en cuando la ventilación. Si afuera hace mucho calor en vez de prender la ventilacion que prenda el aire un rato. 


Es más la estimación de consumo futuro podría incluso tener en cuenta la temperatura externa para así saber si va a ser necesario refrigerar el camper o no entonces guardar más batería.

En cuanto a los tanques.... avisa cuando se están llenando o vaciando, como ya se mencionó y si el tanque de blanca se está quedando sin que corte la corriente de alimentacion de la bomba para evitar que trabaje en vacío.
